### PR TITLE
Fix Issue 1

### PR DESCRIPTION
**Pull request by scaunois**
I replaced the split(" ") to take into account the space character + add a comment to explain how to handle more special charcters.

I also refactor a bit the code. Feel free to get it back as before anf just keep the split() modification if you prefer.

Some things that could be improved :
- add tests cases
- add documentation (or at least comments)

I hope that i helped you !

### CODE REVIEW

**Comment by scaunois** [comment]
Please also note that i am not a git expert, so i tried but unfortunately did not succeed to properly squash my commits to have a unique clean commit.
Feel free to edit it to push a clean commit onto you repo ;)

**Comment by SayantanD99** [comment]
@scaunois Thanks for the help. Got to know a new thing about the split(). I will try to implement the things that you suggested in my future programs. And thanks again !! :)

**Comment by scaunois** [comment]
you are welcome ! Let me know if you have some other difficulties ;)
And please also consider closing the issue on the repo.

Le jeu. 10 janv. 2019 à 18:14, Sayantan Das <notifications@github.com> a
écrit :

**Comment by SayantanD99** [comment]
@scaunois I closed it. And yes I'll let you know if I need any sort of help again. :-)

**Pull request merged**
